version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: kekwait
      MYSQL_DATABASE: rbd
      MYSQL_USER: slave
      MYSQL_PASSWORD: megaslave

    ports:
      - "3340:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

    restart: always
    ports:
      - 8081:80

volumes:
  dbdata: